{% set name = "yaml-lsp" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46f683012791ba78a2d10a8dcc2f638b640952e27c03567168e8ffb99c73a1b8

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - yaml-lsp = yaml_lsp.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - nodejs

test:
  requires:
    - python {{ python_min }}
  imports:
    - yaml_lsp
  commands:
    - test -f ${PREFIX}/bin/yaml-lsp                         # [unix]
    - if not exist %PREFIX%\\Scripts\\yaml-lsp.exe exit 1    # [win]

about:
  home: https://github.com/martinRenou/yaml-lsp
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'YAML language server Python wrapper'
  dev_url: https://github.com/martinRenou/yaml-lsp

extra:
  recipe-maintainers:
    - martinRenou
